name: SurvivalPlugin
version: 1.0
main: io.github.survivalPlugin.main.Main
description: Minigames
api-version: 1.16

commands:

    reset:
        usage: /reset
        
    start:
        usage: /start